### ISSUE TITLE
[範例][帳號計畫] 註冊 TWCC 帳號

### ISSUE THREAD

**Issue by VigaWei** [twcc/TWCC-Docs-en#1]
### Source
中文手冊：
   - HackMD：https://man.twcc.ai/@twccdocs/guide-service-signup-zh  

### To-do
Step1. `[GitHub]` Create a new branch (name: 直接使用 issue 標題)
Step2. 下載 .md 檔案
Step3. 將檔案 commit & push   (目錄：`TWCC-Docs-en/Account & Project/User guides/註冊 TWCC 帳號`)
Step4. 開始進行翻譯工作
  - `[.md]` 最上方 title： `zh` 改為 `en`
  -  `[.md]` 最上方 tags： `ZH` 改為 `EN`
  - `[.md]` 將 `{%hackmd @docsharedstyle/twccheader-zh %}` 改為 `{%hackmd @docsharedstyle/twccheader-en %}`
  - `[.md]` 將中文手冊內容，翻譯成英文、更新截圖

Step5. `[GitHub]` commit & push changes to the branch in Step1 (目錄：`TWCC-Docs-en/Account & Project/User guides/註冊 TWCC 帳號`)
Step6. `[GitHub]` 整篇完成後，create pull request (reviewer 請指定 Viga)

**Comment by twsc-aug** [comment]
slack issue checking
