### ISSUE TITLE
[ISO] 完成資安認知課程

### ISSUE THREAD

**Issue by VigaWei** [twcc/TWCC-Docs-en#294]
### To-do

ISO 27001 要求人員具有基礎資安認知，請完成 企業資安認知宣導 教育訓練，並填寫課後評量，達 80 分 
(課程影片/講義/評量連結另外提供~~)

完成評量後請在下方留言通知 Viga 💬

**Comment by ting88510** [comment]
已完成評量！

**Comment by cxheng315** [comment]
已完成評量！
