### ISSUE TITLE
Revise PRs

### ISSUE THREAD

**Issue by VigaWei** [twcc/TWCC-Docs-en#295]
### To-do

🙇‍♀️ 請幫忙修改下方 PRs 🙇‍♀️ 

Betty：https://github.com/twcc/TWCC-Docs-en/pulls/ting88510

Xing：https://github.com/twcc/TWCC-Docs-en/pulls/cxheng315

**Comment by VigaWei** [comment]
Est hrs: @ting88510 @cxheng315 Thx!

**Comment by ting88510** [comment]
Est hrs: 5hrs
